sudo: required
services:
    - docker

before_install:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
    - docker run -e CI=true ccanning2/react-test

after_success:
    - docker build -t ccanning2/multi-client ./client
    - docker build -t ccanning2/multi-nginx ./nginx
    - docker build -t ccanning2/multi-server ./server
    - docker build -t ccanning2/multi-worker ./worker
    - docker push ccanning2/multi-client
    - docker push ccanning2/multi-nginx
    - docker push ccanning2/multi-server
    - docker push ccanning2/multi-worker

language: generic
